### ISSUE TITLE
embed js

### ISSUE THREAD

**Issue by abhurtun** [daloopa/Embeddable-Widget-Demo#2]
@jeremyhuang1216 can we have the cdn link for it?

**Comment by jeremyhuang1216** [comment]
@abhurtun Yes. The JS bundle is already on CDN. See `Hit from cloudfront` from image below. 

![image](https://user-images.githubusercontent.com/45924211/104629471-695be500-564e-11eb-86b2-20ab5ccebd3d.png)

**Comment by abhurtun** [comment]
👍
